---
- name: Configure EIGRP Lab
  hosts: r1
  connection: network_cli
  gather_facts: no
  tasks:
  - name: Create Loopback Interface
    ios_config:
      lines:
        - ip address 1.1.1.1 255.255.255.255
        - no shutdown
        - description Configured from Ansible
      parents: interface Loopback1
      save_when: modified

  - name: Configure EIGRP
    ios_config:
      lines:
        - network 1.1.1.1 0.0.0.0
        - network 192.168.2.0 0.0.0.255
      parents: router eigrp 1
      save_when: modified