---
- name: Configure EIGRP Lab
  hosts: r1
  connection: network_cli
  gather_facts: no
  tasks:
  - name: Remove EIGRP Lab Information
    ios_config:
      lines:
        - no interface loopback1
        - no router eigrp 1
      save_when: modified